CREATE TABLE IF NOT EXISTS contactos (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre      TEXT NOT NULL,
  correo      TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  creado_en   DATETIME DEFAULT CURRENT_TIMESTAMP
);
